#!/bin/bash

printf '%s\n'
echo -e "working on |...................................|>  $vuln"

VV72261=`grep -i kerberosauth /etc/ssh/sshd_config`
VV72261_1=`grep -i kerberosauth /etc/ssh/sshd_config | head -c1 | wc -c`
VV72261_2=`grep -i kerberosauth /etc/ssh/sshd_config | grep no | head -c1 | wc -c`
VV72261_3=`grep -i kerberosauth /etc/ssh/sshd_config | grep  "^#" | head -c1 | wc -c`
        
FINDING_DETAILS=`echo -e $VV72261`

if [[ $VV72261_1 -eq 1 || $VV72261_2 -eq 1 ||  $VV72261_3 -eq 0 ]]

then

xmlstarlet edit --inplace --update "//VULN[$VULN_COUNT]/STATUS[1]" --value "NotAFinding" $xmlTargetFileName
xmlstarlet edit --inplace --update "//VULN[$VULN_COUNT]/FINDING_DETAILS[1]" --value "$FINDING_DETAILS" $xmlTargetFileName

else
xmlstarlet edit --inplace --update "//VULN[$VULN_COUNT]/STATUS[1]" --value "Open" $xmlTargetFileName
xmlstarlet edit --inplace --update "//VULN[$VULN_COUNT]/FINDING_DETAILS[1]" --value "$FINDING_DETAILS" $xmlTargetFileName

fi

echo -e "...............................................|>  $vuln ${GREEN}[SUCCESS!]${NC}"

