#!/bin/bash

printf '%s\n'
echo -e "working on |...................................|>  $vuln"

VV72259=`grep -i gssapiauth  /etc/ssh/sshd_config`
VV72259_1=`grep -i gssapiauth /etc/ssh/sshd_config | head -c1 | wc -c`
VV72259_2=`grep -i gssapiauth  /etc/ssh/sshd_config | grep no | head -c1 | wc -c`
VV72259_3=`grep -i gssapiauth /etc/ssh/sshd_config | grep  "^#" | head -c1 | wc -c`
        
FINDING_DETAILS=`echo -e $VV72259`

if [[ $VV72259_1 -eq 1 || $VV72259_2 -eq 1 ||  $VV72259_3 -eq 0 ]]

then

xmlstarlet edit --inplace --update "//VULN[$VULN_COUNT]/STATUS[1]" --value "NotAFinding" $xmlTargetFileName
xmlstarlet edit --inplace --update "//VULN[$VULN_COUNT]/FINDING_DETAILS[1]" --value "$FINDING_DETAILS" $xmlTargetFileName

else
xmlstarlet edit --inplace --update "//VULN[$VULN_COUNT]/STATUS[1]" --value "Open" $xmlTargetFileName
xmlstarlet edit --inplace --update "//VULN[$VULN_COUNT]/FINDING_DETAILS[1]" --value "$FINDING_DETAILS" $xmlTargetFileName

fi

echo -e "...............................................|>  $vuln ${GREEN}[SUCCESS!]${NC}"

